apiVersion: apps/v1
kind: Deployment
metadata:
# Define the Deployment Name
  name: nginx-deployment
  labels:
    app: webserver
spec:
# Define the Number of Pods
  replicas: 3
# Define the Selector
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers: # Container Details
      - name: website-nginx
        image: shokhruzd89/website-nginx:latest  # Image
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

