- hosts: kubernetes
  remote_user: ansible
  become: yes
  tasks:
   - name: Install dependencies for Docker
     yum:
      name: yum-utils
      state: present
   
   - name: Remove swapfile from /etc/fstab
     mount:
       name: "{{ item }}"
       fstype: swap
       state: absent
     with_items:
      - swap
      - none

   - name: Disable swap
     command: swapoff -a
   
   - name: Disable IPtables
     command: iptables -F 

  #  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  #    sysctl:
  #     name: net.bridge.bridge-nf-call-ip6tables
  #     value: 1
  #     state: present

  #  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  #    sysctl:
  #     name: net.bridge.bridge-nf-call-iptables
  #     value: 1
  #     state: present  

   
   - name: Add Docker repository
     shell: 
       cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

   - name: add Kubernetes yum repository
     yum_repository:
      name: Kubernetes
      description: kubernetes yum  repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey:  https://packages.cloud.google.com/yum/doc/yum-key.gpg  https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   
   - name: Installing device mapper
     shell: 
       cmd: yum install -y vim epel-release yum-utils device-mapper-persistent-data lvm2

   - name: install Docker
     yum:
       name: docker-ce
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started
  
  #  - name: Remove swapfile from /etc/fstab
  #    mount:
  #      name: "{{ item }}"
  #      fstype: swap
  #      state: absent
  #    with_items:
  #     - swap
  #     - none

  #  - name: Disable swap
  #    command: swapoff -a
   
  #  - name: Disable IPtables
  #    command: iptables -F 

  # - name: disable SELinux
  #   command: setenforce 0
     

  #  - name: disable SELinux on reboot
  #    selinux:
  #      state: disabled

  #  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  #    sysctl:
  #     name: net.bridge.bridge-nf-call-ip6tables
  #     value: 1
  #     state: present

  #  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  #    sysctl:
  #     name: net.bridge.bridge-nf-call-iptables
  #     value: 1
  #     state: present
  
   - name: install kubelet
     yum:
        name: kubelet
        state: present
        update_cache: true
   
   - name: install kubeadm
     yum:
        name: kubeadm
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started 

        

# - hosts: kube_master
#   become: yes
#   tasks:
   - name: install kubectl
     yum:
        name: kubectl
        state: present

   - name: sysctlsystem
     shell:
       cmd: "sysctl --system" 

   

        